version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge
